<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="23897" started-at="2018-03-09T14:10:23Z" finished-at="2018-03-09T14:10:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="23897" started-at="2018-03-09T14:10:23Z" finished-at="2018-03-09T14:10:47Z">
      <class name="price.rule.testcase.ExpiredpriceRule">
        <test-method status="PASS" signature="reports()[pri:0, instance:price.rule.testcase.ExpiredpriceRule@1794d431]" name="reports" is-config="true" duration-ms="120" started-at="2018-03-09T14:10:23Z" finished-at="2018-03-09T14:10:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reports -->
        <test-method status="PASS" signature="loginSc()[pri:1, instance:price.rule.testcase.ExpiredpriceRule@1794d431]" name="loginSc" duration-ms="9396" started-at="2018-03-09T14:10:23Z" finished-at="2018-03-09T14:10:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSc -->
        <test-method status="FAIL" signature="deletePriceRule()[pri:2, instance:price.rule.testcase.ExpiredpriceRule@1794d431]" name="deletePriceRule" duration-ms="14360" started-at="2018-03-09T14:10:32Z" finished-at="2018-03-09T14:10:47Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at price.rule.front.sc.PriceruleDealer.deletePriceRule(PriceruleDealer.java:166)
at price.rule.testcase.ExpiredpriceRule.deletePriceRule(ExpiredpriceRule.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePriceRule -->
      </class> <!-- price.rule.testcase.ExpiredpriceRule -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
